version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:20.10-alpine
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - TG_TOKEN=$TG_TOKEN
    command: npm build; npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s