version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:20.10-alpine
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - TG_TOKEN=$TG_TOKEN
    command: npm build; npm start